# Practice Notebook

### Setup

Import any packages you need in the following cell.

In [2]:
import numpy as np# Task -- Import required packages.

### TASK 1
Re-create the numpy arrays above by entering the lines of code above into the code cell below:

In [5]:
my_array = np.array([1,2,3,4])

In [7]:
type(my_array)

numpy.ndarray

In [10]:
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]])


In [9]:
## Accessing Array Attributes
For this section we retrieving information about the arrays. Once an array is created you can access information about the array such as the number of dimensions, its shape, its size, the data type that it stores, the number of bytes it is consuming. There are a variety of attributes you can use such as:
+ `ndim`
+ `shape`
+ `size`
+ `dtype`
+ `itemsize`
+ `data`
+ `nbytes`

For example, to get the number of dimensions for an array:
```Python
# Print the number of dimensions for the array:
print(my_3d_array.ndim)
```

### Task 2

In the code cell below, practice using each of the attributes above. Add a comment line, as shown in the preceeding code to describe what each attribute is for. Use the [NumPy ndarray reference page](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html) if you need help understanding the attributes.

_Note: Notice that we use dot notation to access these attributes, yet we do not provide the parenthesis `()` like we would for a function call.  This is because we are accessing attributes (i.e. member variables) of the numpy object, we are not calling a function_

SyntaxError: invalid syntax (<ipython-input-9-635cadab056c>, line 2)

In [12]:
my_array.ndim

1

In [14]:
my_array.shape

(4,)

In [16]:
my_array.all()

True

In [18]:
my_array.size

4

In [20]:
help((my_array.all))

Help on built-in function all:

all(...) method of numpy.ndarray instance
    a.all(axis=None, out=None, keepdims=False)
    
    Returns True if all elements evaluate to True.
    
    Refer to `numpy.all` for full documentation.
    
    See Also
    --------
    numpy.all : equivalent function



## Creating Initialized Arrays

Here we will learn to create initialized arrays. Some refer to these as "empty" arrays, but in reality, the arrays are not empty. Rather they are pre-initalized with default values.  NumPy provides a variety of functions for creating and intializing an array in easy-to-use functions. These include: 

+ `np.ones()`
+ `np.zeroes()`
+ `np.random.random()`
+ `np.empty()`
+ `np.full()`
+ `np.arange()`
+ `np.linspace()`

For example, to create an 2-dimesional _3 x 4_ array intialized with all zeros:
```Python
  # Create an array 3x4 array initialized with zeros
  zeros = np.ones((3,4))
```

### TASK 3

Practice creating initialized arrays by using each of the functions above in the code cell below. Just as in the preceeding code example, add a comment above each function call describing what is being done.  Use the [Numpy Function Reference](https://docs.scipy.org/doc/numpy/reference/routines.html) to learn more about each function. Be sure to follow each array creation with a call to `print()` to display your newly created arrays. 

In [22]:
np.ones( 5 )

array([1., 1., 1., 1., 1.])

In [24]:
np.ones( (5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
np.ones( (5, 5, 3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [27]:
np.ones( (2,
          5,
          3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [37]:
np.random.random((4, 6))

array([[0.17349454, 0.69494641, 0.274567  , 0.94335034, 0.38775799,
        0.86161731],
       [0.29805966, 0.52956975, 0.62251529, 0.5449914 , 0.19309142,
        0.23356284],
       [0.56408658, 0.75850943, 0.02276956, 0.78979493, 0.92341538,
        0.53606837],
       [0.34646805, 0.48286985, 0.42285547, 0.01434269, 0.25713302,
        0.66471585]])

In [40]:
demo_d = np.arange(4)
print (demo_d)

[0 1 2 3]


In [42]:
demo_c = np.ones((3,4))
demo_d = np.arange(4)
print(f"demo_c shape: {demo_c.shape}\ndemo_d Shape: {demo_d.shape}")

demo_c shape: (3, 4)
demo_d Shape: (4,)


In [45]:
print(demo_c + demo_d)
print (demo_c)
print(demo_d)

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0 1 2 3]


### Task 4
Try practicing math operations by creating your own arrays of differeing sizes.  In the cell below experiment adding, multiplying or dividing two arrays of different (but compatible) sizes. Do this with two different sets of arrays.

In [33]:
# Task 4.
np.ones((2, 2)) + np.ones((2, 2))

array([[2., 2.],
       [2., 2.]])

In [35]:
demo_a = np.ones((3,4))


In [36]:
my_3d_array


NameError: name 'my_3d_array' is not defined

### Task 5
Find an example of non-compatible array shapes for an operation, and explain why it fails. You can demonstrate using code or written text. If you use written text, be sure to switch the cell below to use Markdown.

# Task 5.
a = np.ones((5,9,3))
b = np.ones((6,8,9,2))
print(a+b)

The print function could not be performed the two arrays are not compatible in their dimensions

## NumPy Aggregate Functions
NumPy also provides a variety of functions that "aggregate" data. 
Examples of aggreagation of data include calculating the sum of every element in the array, calculating the mean, standard deviation, etc.  Below are a few examples of aggregation functions provided by numpy:

+ `np.sum()`
+ `np.min()`
+ `np.max()`
+ `np.cumsum()`
+ `np.mean()`
+ `np.median()`
+ `np.corrcoef()`
+ `np.std()`

For example:
```Python
# Calculate the sum of our demo data from above
np.sum(demo_e)
```


### Task 6
Create three to five arrays (or more as needed) and experiment with each of the aggregation functions above. For each function, add a comment line above it that describes what it does.  Use the [Numpy Function Reference](https://docs.scipy.org/doc/numpy/reference/routines.html) to learn more about each function.

In [48]:
# Task 6
np.sum(demo_c)

12.0

In [50]:
np.min(demo_c)

1.0

In [52]:
np.max(demo_c)

1.0

In [53]:
np.mean(demo_c)

1.0

In [55]:
np.median(demo_c)

1.0

In [57]:
np.corrcoef(demo_c)

C:\Users\Jeanette.Rodriguez\Anaconda3\New folder\lib\site-packages\numpy\lib\function_base.py:2400: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]


array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]])

### Logical Aggregate Functions
When arrays contain boolean values there are additional logical aggregation functions you can use: 

 + `logical_and()`
 + `logical_or()`    
 + `logical_not()`    
 
For example:
```Python
# Two lists of boolean values
a = [True, True, False, False]
b = [False, False, True, True]
# Perform a logical "or":
np.logical_or(a, b)
```

### Task 7

Using the code cell below, practice using each of the three logical aggregate functions listed above.

In [59]:
a = [True, True, False, False]
b = [False, False, True, True]
np.logical_or(a, b)


array([ True,  True,  True,  True])

In [61]:
np.logical_and(a, b)

array([False, False, False, False])

In [62]:
np.logical_not(a, b)

TypeError: return arrays must be of ArrayType

### TASK 8
Perform the following in the code cell below:

1. Create (or re-use) 3 arrays, each containing three dimensions.
2. Slice each of these arrays so that:
    + One element / number is returned.
    + One dimension is returned.
    + A subset of a dimension is returned.
3. What is the difference between `[x:]` and `[x, ...]`? (hint, try on high-dimension arrays).
    
*Exactly what you choose to return is not imporant at this point, the goal of this task is to train you so that if you are given an n-dimension numpy array, you will be able to write an index or slice that returns a subset of desired positions.*

In [64]:
sig_list = demo_c < 0.5
demo_c[sig_list]

array([], dtype=float64)

### TASK 9
In the code cell below, experiment with the following boolean conditionals to generate boolean arrays for indexing:
  + Greater than
  + Less than
  + Equals
  + Combine two or more of the above with:
      + or `|`
      + and `&`

You can create arrays or use existing ones:

In [12]:
# Task 9

### TASK 10

In the code cell below, call `help()` on one of the following functions:
 + `np.transpose()`
 + `np.reshape()`
 + `np.resize()`
 + `np.ravel()`
 + `np.append()`
 + `np.delete()`
 + `np.concatenate()`
 + `np.vstack()`
 + `np.hstack()`
 + `np.column_stack()`
 + `np.vsplit()`
 + `np.hsplit()` 

In [65]:
help(np.transpose)

Help on function transpose in module numpy.core.fromnumeric:

transpose(a, axes=None)
    Permute the dimensions of an array.
    
    Parameters
    ----------
    a : array_like
        Input array.
    axes : list of ints, optional
        By default, reverse the dimensions, otherwise permute the axes
        according to the values given.
    
    Returns
    -------
    p : ndarray
        `a` with its axes permuted.  A view is returned whenever
        possible.
    
    See Also
    --------
    moveaxis
    argsort
    
    Notes
    -----
    Use `transpose(a, argsort(axes))` to invert the transposition of tensors
    when using the `axes` keyword argument.
    
    Transposing a 1-D array returns an unchanged view of the original array.
    
    Examples
    --------
    >>> x = np.arange(4).reshape((2,2))
    >>> x
    array([[0, 1],
           [2, 3]])
    
    >>> np.transpose(x)
    array([[0, 2],
           [1, 3]])
    
    >>> x = np.ones((1, 2, 3))
    >>> np.transpos

### Task 11
Practice appending matricies to one another. In the code cell below perform the following:
 + Create a three dimensional array
 + append another row to the array
 + append another colum to the array
 + print the final results

In [8]:
# Task 11

In [ ]:
# Concatentate `my_array` and `x`: similar to np.append()
my_array = np.array([1,2,3,4])
x = np.array([1,1,1,1])
print("concatenate:")
print(np.concatenate((my_array, x)))

# Stack arrays row-wise
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]])
print("\nvstack:")
print(np.vstack((my_array, my_2d_array)))

# Stack arrays horizontally
print("\nhstack:")
print(np.hstack((my_2d_array, my_2d_array)))

# Stack arrays column-wise
print("\ncolumn_stack:")
print(np.column_stack((my_2d_array, my_2d_array)))


### Task 12
Examine the output from each of the function calls in the cell above. Also, review the help pages for each tool either using the `help()` command or the [Numpy Function Reference](https://docs.scipy.org/doc/numpy/reference/routines.html). Can you identify what is happening with each of them?

In [7]:
# Task 12.

In [ ]:
# Create a 2D array.
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]])
print("original:")
print(my_2d_array)

# Split `my_stacked_array` horizontally at the 2nd index
print("\nhsplit:")
print(np.hsplit(my_2d_array, 2))

# Split `my_stacked_array` vertically at the 2nd index
print("\nvsplit:")
print(np.vsplit(my_2d_array, 2))

### Task 13
Examine the output from each of the functions used in the cell above. Review the help pages for each tool either using the `help()` command or the [Numpy Function Reference](https://docs.scipy.org/doc/numpy/reference/routines.html). Can you identify what is happening with each of them?

In [ ]:
# Task 13